export const QUICK_TEMPLATES = [
  {
    template_key: 'product_launch',
    name: 'Product Launch Campaign',
    description: 'A structured campaign to introduce a new product, feature, or service to a target audience.',
    recommended_duration_weeks: 4,
    default_status: 'planning',
    primary_goal: 'Generate awareness and initial engagement around a new launch',
    stages: ['Pre-Launch Preparation', 'Launch Moment', 'Post-Launch Amplification'],
    planned_deliverables: [
      { deliverable_type: 'post', stage: 'Pre-Launch Preparation', platform: 'instagram', title: 'Product Teaser', description: 'Teaser content', default_due_offset_days: -7, priority: 'high' },
      { deliverable_type: 'post', stage: 'Launch Moment', platform: 'linkedin', title: 'Launch Announcement', description: 'Official announcement', default_due_offset_days: 0, priority: 'high' },
      { deliverable_type: 'post', stage: 'Post-Launch Amplification', platform: 'instagram', title: 'Feature Highlights', description: 'Feature showcase', default_due_offset_days: 3, priority: 'medium' },
    ],
    suggested_metrics: ['reach', 'engagement', 'clicks'],
  },
  {
    template_key: 'awareness_campaign',
    name: 'Brand or Awareness Campaign',
    description: 'A campaign focused on increasing visibility, recognition, or understanding of a brand, cause, or initiative.',
    recommended_duration_weeks: 6,
    default_status: 'planning',
    primary_goal: 'Increase awareness and familiarity among a defined audience',
    stages: ['Audience Research', 'Message Development', 'Distribution', 'Reinforcement'],
    planned_deliverables: [
      { deliverable_type: 'post', stage: 'Distribution', platform: 'instagram', title: 'Educational Content', description: 'Explainer content', default_due_offset_days: 0, priority: 'high' },
      { deliverable_type: 'post', stage: 'Distribution', platform: 'tiktok', title: 'Story-Driven Reel', description: 'Values-based content', default_due_offset_days: 7, priority: 'medium' },
      { deliverable_type: 'post', stage: 'Reinforcement', platform: 'linkedin', title: 'Recap Post', description: 'Reminder post', default_due_offset_days: 28, priority: 'low' },
    ],
    suggested_metrics: ['reach', 'engagement', 'earned_mentions'],
  },
  {
    template_key: 'event_promotion',
    name: 'Event Promotion Campaign',
    description: 'A campaign designed to promote attendance and engagement for an upcoming event.',
    recommended_duration_weeks: 3,
    default_status: 'planning',
    primary_goal: 'Drive awareness and attendance for an event',
    stages: ['Event Announcement', 'Build Momentum', 'Final Push', 'Post-Event Follow-Up'],
    planned_deliverables: [
      { deliverable_type: 'post', stage: 'Event Announcement', platform: 'instagram', title: 'Save-the-Date', description: 'Event announcement', default_due_offset_days: -21, priority: 'high' },
      { deliverable_type: 'email', stage: 'Event Announcement', platform: 'email', title: 'Event Invitation', description: 'Email invitation', default_due_offset_days: -14, priority: 'high' },
      { deliverable_type: 'post', stage: 'Build Momentum', platform: 'linkedin', title: 'Speaker Highlights', description: 'Agenda preview', default_due_offset_days: -7, priority: 'medium' },
      { deliverable_type: 'post', stage: 'Post-Event Follow-Up', platform: 'instagram', title: 'Event Recap', description: 'Thank-you post', default_due_offset_days: 2, priority: 'medium' },
    ],
    suggested_metrics: ['reach', 'engagement', 'attendance'],
  },
  {
    template_key: 'crisis_response',
    name: 'Crisis or Issue Response Campaign',
    description: 'A controlled communications campaign designed to respond to a crisis, issue, or sensitive situation.',
    recommended_duration_weeks: 2,
    default_status: 'active',
    primary_goal: 'Provide clarity, maintain trust, and control the narrative',
    stages: ['Situation Assessment', 'Official Response', 'Ongoing Updates', 'Resolution'],
    planned_deliverables: [
      { deliverable_type: 'press_note', stage: 'Official Response', platform: 'press', title: 'Crisis Statement', description: 'Initial statement', default_due_offset_days: 0, priority: 'high' },
      { deliverable_type: 'post', stage: 'Official Response', platform: 'linkedin', title: 'Public Statement', description: 'Social media statement', default_due_offset_days: 1, priority: 'high' },
      { deliverable_type: 'post', stage: 'Ongoing Updates', platform: 'twitter', title: 'Progress Update', description: 'Update communication', default_due_offset_days: 3, priority: 'medium' },
    ],
    suggested_metrics: ['sentiment', 'engagement', 'media_mentions'],
  },
  {
    template_key: 'partnership_collaboration',
    name: 'Partnership or Collaboration Campaign',
    description: 'A campaign highlighting collaboration between two or more organizations or stakeholders.',
    recommended_duration_weeks: 4,
    default_status: 'planning',
    primary_goal: 'Highlight shared value and expand reach through collaboration',
    stages: ['Alignment', 'Joint Announcement', 'Co-Created Content', 'Wrap-Up'],
    planned_deliverables: [
      { deliverable_type: 'press_note', stage: 'Joint Announcement', platform: 'press', title: 'Partnership Press Release', description: 'Joint announcement', default_due_offset_days: 0, priority: 'high' },
      { deliverable_type: 'post', stage: 'Joint Announcement', platform: 'linkedin', title: 'Partnership Announcement', description: 'LinkedIn announcement', default_due_offset_days: 0, priority: 'high' },
      { deliverable_type: 'post', stage: 'Co-Created Content', platform: 'instagram', title: 'Collaborative Spotlight', description: 'Partnership story', default_due_offset_days: 7, priority: 'medium' },
    ],
    suggested_metrics: ['reach', 'engagement', 'earned_mentions'],
  },
];
